{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "c193fae8-16af-4e9e-aec8-dd70f2d1360e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Dataset loaded successfully.\n",
      "First 10 rows:\n",
      "                                               title       Marca  Preco_Normal  Preco_Desconto  Preco_Anterior  Desconto Categoria\n",
      "0              Pack 12 un, Leche extra proteína 1 L  Loncoleche         19788               0               0         0   lacteos\n",
      "1   Pack 12 un, Leche chocolate receta original 1 L     Soprole         18228               0               0         0   lacteos\n",
      "2    Pack 12 un, Leche semidescremada chocolate 1 L     Soprole         18228               0               0         0   lacteos\n",
      "3     Pack 12 un, Leche semidescremada frutilla 1 L     Soprole         18228               0               0         0   lacteos\n",
      "4       Pack 12 un, Leche sin lactosa chocolate 1 L  Loncoleche         17988               0               0         0   lacteos\n",
      "5        Pack 12 un, Leche sin lactosa frutilla 1 L  Loncoleche         17988               0               0         0   lacteos\n",
      "6  Pack 12 un, Leche saborizada light chocolate 1 L  Loncoleche         17988               0               0         0   lacteos\n",
      "7         Pack 12 un, Leche saborizada frutilla 1 L       Colun         17388               0               0         0   lacteos\n",
      "8         Pack 12 un, Leche saborizada vainilla 1 L       Colun         17388               0               0         0   lacteos\n",
      "9           Pack 12 un, Leche saborizada manjar 1 L       Colun         17388               0               0         0   lacteos\n",
      "Initial Check:\n",
      "                                             title       Marca  Preco_Normal  Preco_Desconto  Preco_Anterior  Desconto Categoria\n",
      "0             Pack 12 un, Leche extra proteína 1 L  Loncoleche         19788               0               0         0   lacteos\n",
      "1  Pack 12 un, Leche chocolate receta original 1 L     Soprole         18228               0               0         0   lacteos\n",
      "2   Pack 12 un, Leche semidescremada chocolate 1 L     Soprole         18228               0               0         0   lacteos\n",
      "3    Pack 12 un, Leche semidescremada frutilla 1 L     Soprole         18228               0               0         0   lacteos\n",
      "4      Pack 12 un, Leche sin lactosa chocolate 1 L  Loncoleche         17988               0               0         0   lacteos\n",
      "                                                 title    Marca  Preco_Normal  Preco_Desconto  Preco_Anterior  Desconto                   Categoria\n",
      "1102                  Helado bresler pote cassata 2,4l  Bresler             0            4359            5449      1090                  congelados\n",
      "1103   Helado Trisabor chocolate lúcuma y manjar 2,4 L  Bresler             0            4359            5449      1090                  congelados\n",
      "1104            Shampoo Reconstrucción Completa 400 ml     Dove             0            2690            3849      1159  belleza-y-cuidado-personal\n",
      "1105         Acondicionador Hidratación Intensa 400 ml     Dove             0            2690            3849      1159  belleza-y-cuidado-personal\n",
      "1106  Leche en Polvo Nido Forticrece Sin lactosa 1440g     Nido             0           14550           18899      4349                     lacteos\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 1107 entries, 0 to 1106\n",
      "Data columns (total 7 columns):\n",
      " #   Column          Non-Null Count  Dtype \n",
      "---  ------          --------------  ----- \n",
      " 0   title           1107 non-null   object\n",
      " 1   Marca           1107 non-null   object\n",
      " 2   Preco_Normal    1107 non-null   int64 \n",
      " 3   Preco_Desconto  1107 non-null   int64 \n",
      " 4   Preco_Anterior  1107 non-null   int64 \n",
      " 5   Desconto        1107 non-null   int64 \n",
      " 6   Categoria       1107 non-null   object\n",
      "dtypes: int64(4), object(3)\n",
      "memory usage: 60.7+ KB\n",
      "title             object\n",
      "Marca             object\n",
      "Preco_Normal       int64\n",
      "Preco_Desconto     int64\n",
      "Preco_Anterior     int64\n",
      "Desconto           int64\n",
      "Categoria         object\n",
      "dtype: object\n",
      "Null Value Analysis:\n",
      "title             0\n",
      "Marca             0\n",
      "Preco_Normal      0\n",
      "Preco_Desconto    0\n",
      "Preco_Anterior    0\n",
      "Desconto          0\n",
      "Categoria         0\n",
      "Preco_R$          0\n",
      "Unidades          0\n",
      "Preco_Unitario    0\n",
      "dtype: int64\n",
      "title             0.0\n",
      "Marca             0.0\n",
      "Preco_Normal      0.0\n",
      "Preco_Desconto    0.0\n",
      "Preco_Anterior    0.0\n",
      "Desconto          0.0\n",
      "Categoria         0.0\n",
      "Preco_R$          0.0\n",
      "Unidades          0.0\n",
      "Preco_Unitario    0.0\n",
      "dtype: float64\n",
      "                                             title       Marca  Preco_Normal  Preco_Desconto  Preco_Anterior  Desconto Categoria  Preco_R$  Unidades  Preco_Unitario\n",
      "0             Pack 12 un, Leche extra proteína 1 L  Loncoleche         19788               0               0         0   lacteos    197.88        12           16.49\n",
      "1  Pack 12 un, Leche chocolate receta original 1 L     Soprole         18228               0               0         0   lacteos    182.28        12           15.19\n",
      "2   Pack 12 un, Leche semidescremada chocolate 1 L     Soprole         18228               0               0         0   lacteos    182.28        12           15.19\n",
      "3    Pack 12 un, Leche semidescremada frutilla 1 L     Soprole         18228               0               0         0   lacteos    182.28        12           15.19\n",
      "4      Pack 12 un, Leche sin lactosa chocolate 1 L  Loncoleche         17988               0               0         0   lacteos    179.88        12           14.99\n",
      "                                             title    Marca  Preco_Normal  Preco_Desconto  Preco_Anterior  Desconto Categoria  Preco_R$  Unidades  Preco_Unitario\n",
      "808             Yoghurt batido sabor damasco 120 g  Soprole           229               0               0         0   lacteos      2.29         1            2.29\n",
      "809           Yoghurt batido sabor frambuesa 120 g  Soprole           229               0               0         0   lacteos      2.29         1            2.29\n",
      "810   Yoghurt batido semidescremado vainilla 120 g    Calan           209               0               0         0   lacteos      2.09         1            2.09\n",
      "811   Yoghurt batido semidescremado frutilla 120 g    Calan           209               0               0         0   lacteos      2.09         1            2.09\n",
      "812  Yoghurt batido semidescremado chirimoya 120 g    Calan           209               0               0         0   lacteos      2.09         1            2.09\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "Index: 813 entries, 0 to 812\n",
      "Data columns (total 10 columns):\n",
      " #   Column          Non-Null Count  Dtype  \n",
      "---  ------          --------------  -----  \n",
      " 0   title           813 non-null    object \n",
      " 1   Marca           813 non-null    object \n",
      " 2   Preco_Normal    813 non-null    int64  \n",
      " 3   Preco_Desconto  813 non-null    int64  \n",
      " 4   Preco_Anterior  813 non-null    int64  \n",
      " 5   Desconto        813 non-null    int64  \n",
      " 6   Categoria       813 non-null    object \n",
      " 7   Preco_R$        813 non-null    float64\n",
      " 8   Unidades        813 non-null    int64  \n",
      " 9   Preco_Unitario  813 non-null    float64\n",
      "dtypes: float64(2), int64(5), object(3)\n",
      "memory usage: 69.9+ KB\n",
      "Unique Values:\n",
      " title             781\n",
      "Marca             127\n",
      "Preco_Normal      360\n",
      "Preco_Desconto      1\n",
      "Preco_Anterior      1\n",
      "Desconto            1\n",
      "Categoria           7\n",
      "Preco_R$          360\n",
      "Unidades            7\n",
      "Preco_Unitario    349\n",
      "dtype: int64\n",
      "Descriptive Statistics:\n",
      "        Preco_Normal  Preco_Desconto  Preco_Anterior  Desconto    Preco_R$  \\\n",
      "count    813.000000           813.0           813.0     813.0  813.000000   \n",
      "mean    2819.918819             0.0             0.0       0.0   28.199188   \n",
      "std     3135.210940             0.0             0.0       0.0   31.352109   \n",
      "min      209.000000             0.0             0.0       0.0    2.090000   \n",
      "25%      990.000000             0.0             0.0       0.0    9.900000   \n",
      "50%     1890.000000             0.0             0.0       0.0   18.900000   \n",
      "75%     3290.000000             0.0             0.0       0.0   32.900000   \n",
      "max    19788.000000             0.0             0.0       0.0  197.880000   \n",
      "\n",
      "         Unidades  Preco_Unitario  \n",
      "count  813.000000      813.000000  \n",
      "mean     1.706027       21.572302  \n",
      "std      2.395794       19.663586  \n",
      "min      1.000000        2.090000  \n",
      "25%      1.000000        8.490000  \n",
      "50%      1.000000       15.890000  \n",
      "75%      1.000000       29.990000  \n",
      "max     12.000000      167.990000  \n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import re\n",
    "from pathlib import Path\n",
    "\n",
    "def load_and_clean_data(filepath):\n",
    "    # Usa Path para garantir compatibilidade multiplataforma\n",
    "    filepath = Path(filepath)\n",
    "\n",
    "    # Verifica se o arquivo existe\n",
    "    if not filepath.exists():\n",
    "        raise FileNotFoundError(f\"Arquivo não encontrado: {filepath}\")\n",
    "\n",
    "    # Carrega o dataset\n",
    "    df = pd.read_csv(filepath)\n",
    "    print('Dataset loaded successfully.')\n",
    "    print('First 10 rows:\\n', df.head(10).to_string())\n",
    "\n",
    "    # Inspeção inicial\n",
    "    print('Initial Check:')\n",
    "    print(df.head().to_string())\n",
    "    print(df.tail().to_string())\n",
    "    df.info()\n",
    "    print(df.dtypes)\n",
    "\n",
    "    # Converte preço de centavos para reais\n",
    "    if 'Preco_Normal' in df.columns:\n",
    "        df['Preco_R$'] = df['Preco_Normal'] / 100\n",
    "    else:\n",
    "        raise KeyError(\"Coluna 'Preco_Normal' não encontrada no CSV.\")\n",
    "\n",
    "    # Extrai quantidade de unidades do título\n",
    "    if 'title' in df.columns:\n",
    "        df['Unidades'] = df['title'].str.extract(r'Pack (\\d+) un').astype(float)\n",
    "    else:\n",
    "        raise KeyError(\"Coluna 'title' não encontrada no CSV.\")\n",
    "\n",
    "    # Preenche valores ausentes com 1\n",
    "    df['Unidades'] = df['Unidades'].fillna(1).astype(int)\n",
    "\n",
    "    # Remove linhas com preço zero ou nulo\n",
    "    df = df[(df['Preco_R$'] != 0) & (df['Preco_R$'].notna())]\n",
    "\n",
    "    # Calcula preço unitário\n",
    "    df['Preco_Unitario'] = df['Preco_R$'] / df['Unidades']\n",
    "\n",
    "    # Análise de valores nulos\n",
    "    print('Null Value Analysis:')\n",
    "    print(df.isnull().sum())\n",
    "    print((df.isnull().mean() * 100).round(2))\n",
    "\n",
    "    # Checagem final\n",
    "    print(df.head().to_string())\n",
    "    print(df.tail().to_string())\n",
    "    df.info()\n",
    "\n",
    "    # Valores únicos e estatísticas\n",
    "    print('Unique Values:\\n', df.nunique())\n",
    "    print('Descriptive Statistics:\\n', df.describe())\n",
    "\n",
    "    return df\n",
    "\n",
    "# Exemplo de uso:\n",
    "df = load_and_clean_data(\"data/raw/MODULO7_PROJETOFINAL_BASE_SUPERMERCADO.csv\")\n",
    "# filepath = r\"data/raw/MODULO7_PROJETOFINAL_BASE_SUPERMERCADO.csv\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c5c501f9-811e-47d8-a360-6264e468331a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
